apiVersion: v1
kind: Service
metadata:
  name: ai-k8s-troubleshooter
spec:
  selector:
    app: ai-k8s-troubleshooter
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
